# Last update April 2024 (rlh)
server:
  port: 9000

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5452/authdb
    username: "{cipher}AQCTdPK7+bJ/5VjtHoK3/7Y7QfjMu0E1cJLrikJmtWonXZ8FyMM6kgt7Xb/nDXVHtK6A1lTySuXcrVt8oIqrApDA5AVKzChktGbfC8pJKxWmhgRZH0pkrblyP4wcjdtZNMATruZFg/F1//awhksn9Z+ZgvoIerXwr/BR/0yJJnMpQd+yxes48dUtK0RT89QxnFo4TzynBjYUcy0jaAB+/RXrGdqhQpb7HoZjJKsU4kQFvBwit+c02z7Cb955Sg+gcGocaCvZ8l7zlose1dCymXfLR4F8y5GtJlghShXrMnSraq2VUd/zJJJbfDmnIDzQ8sEPqpsyx1adEipBT+4U3ZAKepuL97NEy/4gZ+FaEggTGCM7olhyju/t7yIDe1GShe8="
    password: "{cipher}AQAVyFHOd3acr/YbSSLOXlhnPvF5ssyI0EweQzcK0uM1TNtNjWQWUZI+kqOJ6TzKIqwK6MmSsmT6DnUpArEKO57x+bMw4VYdppnfZsedKQrKsB3bXVfuzhripuBjJ0vudaJAsGEI2OTm+im3ds/l/IWdAse2fnmBtn9UsM7P87TfPVZpxre4XHSmWzAKH1ufhpMGGyc84PRIzlCVb7c1drtjuOAbW1/l3XG7pZHkgSmrmc+pPkfYVoqwLWOZl5aM1ea8D4Eazv21UlEqF7pYRThET7c3OI1MAru75GR+wEcctZlxidtJfRp7v78yDHX+FZLxXzR22YmpDUVA98t5iKw1ITH1k95LODOEubDomEQLSctSiBaOJv2yf6ej8f+H/Oc="
    hikari:
      connection-timeout: 2000  # The maximum time (ms) to spend waiting to get a connection from the pool
      maximum-pool-size: 5      # The maximum number of connections HikariCP will keep in the pool
  r2dbc:
    username: "{cipher}AQCTdPK7+bJ/5VjtHoK3/7Y7QfjMu0E1cJLrikJmtWonXZ8FyMM6kgt7Xb/nDXVHtK6A1lTySuXcrVt8oIqrApDA5AVKzChktGbfC8pJKxWmhgRZH0pkrblyP4wcjdtZNMATruZFg/F1//awhksn9Z+ZgvoIerXwr/BR/0yJJnMpQd+yxes48dUtK0RT89QxnFo4TzynBjYUcy0jaAB+/RXrGdqhQpb7HoZjJKsU4kQFvBwit+c02z7Cb955Sg+gcGocaCvZ8l7zlose1dCymXfLR4F8y5GtJlghShXrMnSraq2VUd/zJJJbfDmnIDzQ8sEPqpsyx1adEipBT+4U3ZAKepuL97NEy/4gZ+FaEggTGCM7olhyju/t7yIDe1GShe8="
    password: "{cipher}AQAVyFHOd3acr/YbSSLOXlhnPvF5ssyI0EweQzcK0uM1TNtNjWQWUZI+kqOJ6TzKIqwK6MmSsmT6DnUpArEKO57x+bMw4VYdppnfZsedKQrKsB3bXVfuzhripuBjJ0vudaJAsGEI2OTm+im3ds/l/IWdAse2fnmBtn9UsM7P87TfPVZpxre4XHSmWzAKH1ufhpMGGyc84PRIzlCVb7c1drtjuOAbW1/l3XG7pZHkgSmrmc+pPkfYVoqwLWOZl5aM1ea8D4Eazv21UlEqF7pYRThET7c3OI1MAru75GR+wEcctZlxidtJfRp7v78yDHX+FZLxXzR22YmpDUVA98t5iKw1ITH1k95LODOEubDomEQLSctSiBaOJv2yf6ej8f+H/Oc="
    url: r2dbc:postgresql://localhost:5452/authdb
    pool:
      max-create-connection-time: 2s
      initial-size: 5
      max-size: 10
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: "{cipher}AQCb1dNPJXb5RIUDndQpFEQRIFhr6Y5hy9x/okwpobUaUS0yFlAQWKHXvnwyZY2kMWRkWBrYSAAgT2ei85mYuEit6pgUnJx7ieRp/Oz1A1F71Asg0SyxihunjF4v9KYYAMfRnsQMzFhYpJu2npZXoo7xrt7lma7EXOVGEAsFSMTBRug9IwJgtG9FT7rcm+XRElK2CLYwGyoEMdW19vFM6hJNnQHB99S33nhY4u/MP02139C7MCS6Csb9qQZmj/PYjZ+w42JLz/44ZPdJnJPWr7x132fFePXC4fawJpkUZPwiMcpdC4r/TsAVOEYiL7l3tE+m3LQTjixI3D2jgM5kCjxZtv172SeyFadEgDMOty8El/CYcPY8f/cudECFwz275N0="
      password: "{cipher}AQAmiaJIlGQ1fPNSt/8HnScbOk2hTf2ZdJ3DYdpq0/AfdNgPUQHm3y6CpAMmRtfrIgkojBG1b9Agr5KUMc+p1Y8/gJcUImKG7eb4m86FjlHJUv2f/ewq9CdiMnvkfokZF0Hcdx1PviMX5LZBy32vpJYGF+LLhBgQxeAetkmFG1THaJieE/Zw+5pTR2CsnnBWC5aiUvDccAntEcQJgq0tbpuetGFFd4AuUTyvyuwzhaaMmv5OJjnsStPX3p3xZ3y3UX2V7beWBSe3GO1IYRDePRRMgicuIcrkypBTTE3l4rEbmgPoKFnBdkmklUXvG57CELXLsWCCjpF9gdx18TE00igv7I4DyIGdZB2cV1huuO+O0TC2VS2xEAQzrcuHV6qitac="

# Configuration properties for OpenLDAP: Docker image osixia/openldap
auth:
  ldap:
    uri: ldap://localhost:389
    adminuser: "{cipher}AQBdQW5WpaAUSmlxjjYN5wfrsEsQAVaMqVjbIcg0jzCd9S3WlwgQ4X4gtWkHFgkUGQjxKZLpjmWelyJ0dm4QCnNIu8C11z0SY8gPq2RPR1lupMmICwpi+nYt4mHM8PrkznrZau70LuOGaECEux1wBy310HY9ot2YzLaMD8wV7Rm7r2rmmgvyo7j+lnT5vsP/umy+n99eeQfTP7UIhpOaog4BH8IO9JdFqfkteK8zNXESW2YgO4NpqMi8GirSI8CM91WKjnFKgW0JDovAWLHec0TYG8T3X5ucv7jhvqvmCScT2EGewvjJE36zwLzJFujSTfx8el1b+Qz/JdS19+a5ml/XwiiLuu9Lu1wa8AcXvWXLWdFx3JyTh/3QLcFCa8DuULOcn7s4WwuKhH/Xe4iZO+MS"
    credentials: "{cipher}AQCO8P3dtj+spCjT0M0NUrbeHxXx15Ws6W2Jejruzl33+FQYDBSSYBW3g4tTYcOMOsew0xGQoaDUJMCRDdCaWhf8eDyPg/zIQ1IHnYnjMegkvr6aYRKyHGNN1shYsk1mj9Vm/kDBUoFqAAe7JKTDRop/2Dxw0ezcv0fnys5bJoWV7wOz3mLwh7KJ6LPp84+on6rE099+ZmVWfwbi7Zt5M8r0cjdl1TR4yH/bwLekg/a7m4VliTKXTv4ilRj7aOeysGjtUfatRtnh3waEN6xL7smiFeiowxJo3JteBHkefnBi2j5zIJhB+IcK8MgAD+OxTKurJDZdTCH6oydx8OWhlumFRHaQ2+/j3+7CFGR+mxnX7jQuWodvb7gul5+2e92KGFY="
  neo4j:
    flyway:
      locations: /db/neo4j/migration # Script to initialize iamDB (also in iam-service)
  greeting: "Welcome to Avemex auth microservice from the config service, 'default configuration'."
