# Last update April 2024 (rlh)
server:
  port: 8352

spring:
  mail:
    password: "{cipher}AQB9KObwMdH6xcVcFoOy+kVE1KDjyIZy2aRm0qy4HR/t2iVCLTB6tx4eDgVKzHWswgnMY1Ukm8gyPf5AzEOyFthaVapaNyGtIEDS2LD00DbyPh0rRIQhn1IFaEevl+nqdjUUWxxgyOGn5IEzkxb7ooYL5ZmDvifg9xJPE/TV6c/wNhV58UaFzDPya6BMFk6J6pJTskLuQzGYqAff/1pesghvgJpNGXBYesW5ViipFMUMM34/iHYBi7VO3RYnzBOtfUrLsfYr/jMRzUvjVll17HgEL2GMloJrCuqaMEj/Uua9HMHdWOKnT2MbU0QpQdp0+Y+0Rcu9J75vqiPIwlXYygaqRfh43SlPsc8B+VkFgeUBQkLrQAPqgG4bDnkduYo2ffs="

# Testing what environment we are using
mail:
  greeting: "Welcome to avemex mail microservice from the config server, 'localNoDocker configuration'."