# Last update April 2024 (rlh)
server:
  port: 8520

spring:
  neo4j:
    authentication:
      username: "{cipher}AQAe9WsYH8pK2jaEyUnGG5dpMAcInpBDiiDOOpXAViGKM5WC3SgN0nQH6Y5ltG6eMzyTAWdwUAXJ1EX3rgiRUYUQCqRXlkAVAuSRjjpIGaP1aAN/h9fzN5MWb1rSB/J7dI9IGGsYSG+ItzDLSJ85gQZBcWy41gYSSTjj2nBEGzGKuDVIJPeI0oBZ3xNaUiRCT+n7t9dqqzxrlSRN5kJJXf7jAxOFZCrE0C/F6oxHo2SHpWEb2Cs85pBTU83QwY9LcFwWQQjPSPTKO9ziYUJgT7TF8v+NCPWenLWGnincoGTMZI2GdnXBAcrB1algZhRFDgKuDihSp7Nrr0K0sQL4g5KaxGxYqaDJerumh4AiNVEmHN6Mszg8G4tGrl5Yrf+utjM="
      password: "{cipher}AQBwHBgFJgP6eLpZptCLi5birJdIgeUaaULPbAag6NLHUPVjfkk3um7hv9pdYRAGdeirpsOjmgf+JI85LAnNsSskOvuGB3COffMwe/kk9RmFkmuRb3ONg1xVF/Sydm2IneXVAuznU+jggdnAhA+HRo4/Mv9oZYwM70cmLMgf6yFyLp0YChtG7I6SMV/efGCabQjU4BDeKUMtHk1qtxXRR8iu7vKiUjli7ElOHhjs3+/XINiErpzrG4bcefB8G4+C05PKZsqkobo7U65k+ITR+0FAaccVAjV52qC67+KIXwSB+JngWaMkio1JW1FI5eVBCK0w8gOcBJNZ9A0U88EIoNJlGfUdfLOVzfnEZr3hpkXgY3WKaZ72lVagFV/Ov3CoA1U="

bi:
  greeting: "Welcome to bi microservice from the config server, 'default configuration'."


