# Last update September 2024 (rlh)
server:
  port: 8180

spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: "{cipher}AQCb1dNPJXb5RIUDndQpFEQRIFhr6Y5hy9x/okwpobUaUS0yFlAQWKHXvnwyZY2kMWRkWBrYSAAgT2ei85mYuEit6pgUnJx7ieRp/Oz1A1F71Asg0SyxihunjF4v9KYYAMfRnsQMzFhYpJu2npZXoo7xrt7lma7EXOVGEAsFSMTBRug9IwJgtG9FT7rcm+XRElK2CLYwGyoEMdW19vFM6hJNnQHB99S33nhY4u/MP02139C7MCS6Csb9qQZmj/PYjZ+w42JLz/44ZPdJnJPWr7x132fFePXC4fawJpkUZPwiMcpdC4r/TsAVOEYiL7l3tE+m3LQTjixI3D2jgM5kCjxZtv172SeyFadEgDMOty8El/CYcPY8f/cudECFwz275N0="
      password: "{cipher}AQAmiaJIlGQ1fPNSt/8HnScbOk2hTf2ZdJ3DYdpq0/AfdNgPUQHm3y6CpAMmRtfrIgkojBG1b9Agr5KUMc+p1Y8/gJcUImKG7eb4m86FjlHJUv2f/ewq9CdiMnvkfokZF0Hcdx1PviMX5LZBy32vpJYGF+LLhBgQxeAetkmFG1THaJieE/Zw+5pTR2CsnnBWC5aiUvDccAntEcQJgq0tbpuetGFFd4AuUTyvyuwzhaaMmv5OJjnsStPX3p3xZ3y3UX2V7beWBSe3GO1IYRDePRRMgicuIcrkypBTTE3l4rEbmgPoKFnBdkmklUXvG57CELXLsWCCjpF9gdx18TE00igv7I4DyIGdZB2cV1huuO+O0TC2VS2xEAQzrcuHV6qitac="

iam:
  greeting: "Welcome to avemex iam microservice from the config server, 'default configuration'."


