# Last update April, 2024 (rlh)
server:
  port: 8300

mongodb:
  username: "{cipher}AQAp4zyDXNqhHeQubVsVJX1gIrQlW+DsTYjfAyHT0AGqnXXb10pV4SAoCIlIsCbFqrY7oGRfS7dtTV64JZF/nIzRT0U1A9ekVOMxYRjJ6ZWO+/swyzLv/AGS97qF8kfqqzqDq9R1dgIQfOE2Q8O0SyMqQaAzXStoluVAVKoCUW/0g1Pt5st9qoO+ZfbJeUYvz/F2UXdqLY7XcbNbnjanzb0xY8jrALwtl9AtutaBx/colPvUX4WKmKHILFcWfS/MMQv/EuSv6wLrCux88t1AGixqpNyRkVwZ/J4cvwCexAWKdOw7PAk7G+obYyWjoqllbdGKS0XjZxyXm05Br9MRXj962i/cTWjk2N0RXMfIfsy6rSY286aueyPWBgPw45CExSI="
  password: "{cipher}AQA+ldSIscnPxZ2XLYkeOHDW+m2LxuP2oUE5lPWnX3wlMhb+BJ7jfs5SU01w3CtUaD2/rcobtsUCmnVXrviv5NKbWJ89PPGMeHm7GAXG4SB02y9eHtayp+x6tiEXFPAIbOwEyrkPlu9DlMYsDqUfwOBKMxGzATe83PG2hO9ObuousouwrgW8VrH3fKc2InTCOuyZ32smHYsGKL2YAPHGSuNg7QYnBcNNbEFqpZExHIH5vcCI+w8bVXni+i2kqM2rx5bd3U0ub7UMEjfJfFOrQmCMW8WbkJ65er5dMAN3yjXCz4umH87ckCN8Fokr78HYNgGLjPtotilw65zdYKv7WvvHHgeosk/g108x6F0DGLgFBBFL2vo0ZUBRqdhKRWebG88="

spring:
  data:
    mongodb:
      # note: Spring boot 3.1.0 ignores Mongo properties authentication database.
      # see:https://github.com/spring-projects/spring-boot/issues/35632
      # The workaround is to use mongo uri
      uri: mongodb://${mongodb.username}:${mongodb.password}@localhost/events?authSource=admin

# Testing what environment we are using
audit:
  greeting: "Welcome to avemex audit microservice from the config server, 'default configuration'."