# Last update April 2024 (rlh)
server:
  port: 8350

eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: avemex-param-service
  client:
    healthcheck:
      enabled: true         # this must be true because it is a service
    serviceUrl:
      defaultZone: http://avemex-eureka-service:8070/eureka/
    registerWithEureka: true
    fetchRegistry: false      # this must be false because it is a service

spring:
  datasource:
    url: jdbc:postgresql://avemex-postgres:5452/paramdb
    username: "{cipher}AQB5hvWgi72Ue5MwqN/EnAScAXXm9XTavFekVG3JPXwV/Q76h5s3pS8RxEjap8e4iTEl8StwokoxScwR6nqAN+BkB88slXcPoVohKYdmGdBtDsO3MCr+nJySNB3EqR4gQvMh60TGhh6liNkaPZ8iPeRBy/jCOpSVhFqJ8AiQs+V6V73fK99NzdVBTtaPzV0Tk5wd1nB7GE6NZZ38RFF6ghP++FuL1V7v06/OKex8BZaRY1EwVqdU+MHQSe9fMcfOvAlsprSKLQXVu4AHbPccpX36LvKesvE1tJP4YohNI3OI6K9KBGj5VHuUAnoWTFqQMPbVAEnnaJSt7TBy/82vLl3aX6hDJjGLCcgaKzPryRgqMS4427Ut490T9TrrHKTHKJI="
    password: "{cipher}AQCZuzdf4lGkLt0Rs2DH1eA3ByixwCsImQMwGQ59SV6gOFuF0CouRJ0RK4RFrfzL8I/nSSpZZIabDqsYI0feVHK8qo8bJWHYpYGQlEJijbxakXjqxh9wYZ+8bqWGaPgLRNBUjamA03uyJBUhrrxT85FHe9/FhqQqJEEFgsSHeEZUqYxrFMWSHHU7Lbj8GUFQ+BOIaA6MrOoGq+aOr9H20+ju8CY1F1Qix+Fr3q67cw+ENNtX309BG/2cgimpql0UmilFE+UV3yl1oXI4hPlnyCh1G8Hf9qZNvDDvWnZWaC/QFq/rRhFL/HPuea5ZjLg1h6VkT6cygRXo8VI68LQ/vcO7YnRLQTldHo6KwHUu9SpSyTydfmRhIjJ09vZeEJYOmr8="

# Testing what environment we are using
param:
  greeting: "Welcome to avemex param microservice from the config server, 'docker configuration'."
