# Configuration for running the avemex-sys-ui outside a Docker
# Last update April 2024 (rlh)
server:
  port: 8360
  
eureka:
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.int}
    hostname: avemex-sys-ui
  client:
    healthcheck:
      enabled: false # this must be false because is a UI
    registerWithEureka: true
    fetchRegistry: true       # this must be true because is UI
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
    registry-fetch-interval-seconds: 5

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

security:
  iam:
    provider-uri: http://localhost:8072/avemex/iam-service       # use the gateway
    load-balanced: false
